// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrXOuEM9ULEg-VrPsDbXsscsG3DGNb0P4',
    appId: '1:731123317224:web:3a12f469fdc976dfde8c5d',
    messagingSenderId: '731123317224',
    projectId: 'igrejansl-89d79',
    authDomain: 'igrejansl-89d79.firebaseapp.com',
    databaseURL: 'https://igrejansl-89d79-default-rtdb.firebaseio.com',
    storageBucket: 'igrejansl-89d79.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcbi22N9B1jZrRylf2EBRZRB0kaThg6uo',
    appId: '1:731123317224:android:31e3af3282797b9fde8c5d',
    messagingSenderId: '731123317224',
    projectId: 'igrejansl-89d79',
    databaseURL: 'https://igrejansl-89d79-default-rtdb.firebaseio.com',
    storageBucket: 'igrejansl-89d79.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKFfQdCA0byl2VdPxO4HFwx3n_4pje-2g',
    appId: '1:731123317224:ios:e6c50283cc4e7844de8c5d',
    messagingSenderId: '731123317224',
    projectId: 'igrejansl-89d79',
    databaseURL: 'https://igrejansl-89d79-default-rtdb.firebaseio.com',
    storageBucket: 'igrejansl-89d79.appspot.com',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKFfQdCA0byl2VdPxO4HFwx3n_4pje-2g',
    appId: '1:731123317224:ios:e6c50283cc4e7844de8c5d',
    messagingSenderId: '731123317224',
    projectId: 'igrejansl-89d79',
    databaseURL: 'https://igrejansl-89d79-default-rtdb.firebaseio.com',
    storageBucket: 'igrejansl-89d79.appspot.com',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDpXJvnr0j6xOKootJKIapyDlZnWUyRb4w',
    appId: '1:731123317224:web:803226300acec5b1de8c5d',
    messagingSenderId: '731123317224',
    projectId: 'igrejansl-89d79',
    authDomain: 'igrejansl-89d79.firebaseapp.com',
    databaseURL: 'https://igrejansl-89d79-default-rtdb.firebaseio.com',
    storageBucket: 'igrejansl-89d79.appspot.com',
  );
}
